[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/golang/glog"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  source = "github.com/grpc/grpc-go"
  branch = "master"