// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serial.proto

/*
Package serial is a generated protocol buffer package.

It is generated from these files:
	serial.proto

It has these top-level messages:
	Empty
	Response
*/
package serial

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 請求
type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 回應
type Response struct {
	No uint64 `protobuf:"varint,1,opt,name=No" json:"No,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetNo() uint64 {
	if m != nil {
		return m.No
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "serial.Empty")
	proto.RegisterType((*Response)(nil), "serial.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SerialServicee service

type SerialServiceeClient interface {
	Get(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error)
}

type serialServiceeClient struct {
	cc *grpc.ClientConn
}

func NewSerialServiceeClient(cc *grpc.ClientConn) SerialServiceeClient {
	return &serialServiceeClient{cc}
}

func (c *serialServiceeClient) Get(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/serial.SerialServicee/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SerialServicee service

type SerialServiceeServer interface {
	Get(context.Context, *Empty) (*Response, error)
}

func RegisterSerialServiceeServer(s *grpc.Server, srv SerialServiceeServer) {
	s.RegisterService(&_SerialServicee_serviceDesc, srv)
}

func _SerialServicee_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialServiceeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serial.SerialServicee/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialServiceeServer).Get(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _SerialServicee_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serial.SerialServicee",
	HandlerType: (*SerialServiceeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SerialServicee_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serial.proto",
}

func init() { proto.RegisterFile("serial.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0xca,
	0x4c, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xd8, 0xb9, 0x58,
	0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x95, 0xa4, 0xb8, 0x38, 0x82, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x85, 0xf8, 0xb8, 0x98, 0xfc, 0xf2, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x82, 0x98, 0xfc,
	0xf2, 0x8d, 0xac, 0xb8, 0xf8, 0x82, 0xc1, 0xca, 0x83, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x53,
	0x85, 0x34, 0xb8, 0x98, 0xdd, 0x53, 0x4b, 0x84, 0x78, 0xf5, 0xa0, 0x86, 0x82, 0xcd, 0x90, 0x12,
	0x80, 0x71, 0x61, 0x26, 0x29, 0x31, 0x24, 0xb1, 0x81, 0xed, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x45, 0xc8, 0xd6, 0xd2, 0x7f, 0x00, 0x00, 0x00,
}
